# ==== builder stage ====
FROM node:15.7-buster-slim as builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# ==== server stage ====
FROM node:15.7-buster-slim as server

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --only=production

COPY --from=builder /app/.next ./.next

CMD ["npm", "run", "start"]