version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: mpa-server-prod
    container_name: mpa-server-prod
    ports:
      - 3000:3000

  database:
    image: postgres:13.1
    container_name: mpa-database-prod
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mpa
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mpa