version: '3'

services:
  front:
    build:
      context: ./front/
      dockerfile: ./docker/Dockerfile.prod
    image: mpa-front-prod
    container_name: mpa-front-prod
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL_BASE=http://localhost:3000/
  
  api:
    build:
      context: ./api/
      dockerfile: ./docker/Dockerfile.prod
    image: mpa-api-prod
    container_name: mpa-api-prod
    working_dir: /app
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://mpa:password@host.docker.internal:5432/mpa