version: "3"

services:
  server:
    image: node:15.5-buster
    container_name: mpa-server-dev
    command: "npm run dev"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://mpa:password@database:5432/mpa

  database:
    image: postgres:13.1
    container_name: mpa-database-dev
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mpa
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mpa