version: '3'

services:
  load-balancer:
    image: nginx:1.18.0-alpine
    container_name: mpa-load-balancer-dev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api
      - front
    
  front:
    build:
      context: ./front/
      dockerfile: ./docker/Dockerfile.dev
    image: mpa-front-dev
    container_name: mpa-front-dev
    working_dir: /app
    volumes:
      - /app/.next
      - /app/node_modules
      - ./front:/app:cached
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
  
  api:
    build:
      context: ./api/
      dockerfile: ./docker/Dockerfile.dev
    image: mpa-api-dev
    container_name: mpa-api-dev
    working_dir: /app
    volumes:
      - /app/build/build
      - /app/build/src
      - /app/node_modules
      - ./api:/app:cached
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://mpa:password@database:5432/mpa

  database:
    image: postgres:13.1-alpine
    container_name: mpa-database-dev
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mpa
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mpa
