version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    image: mpa-server-dev
    container_name: mpa-server-dev
    working_dir: /app
    volumes:
      - /app/.next
      - /app/node_modules
      - ./:/app:cached
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://mpa:password@database:5432/mpa
      - NEXT_PUBLIC_API_URL_BASE=http://localhost:3000/api

  database:
    image: postgres:13.1
    container_name: mpa-database-dev
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mpa
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mpa
