version: '3'

services:
  front:
    build:
      context: ./front/
      dockerfile: ./docker/Dockerfile.prod
    image: mpa-front-prod
    container_name: mpa-front-prod
    working_dir: /app
    ports:
      - 3333:3000
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL_BASE=http://localhost:3000/
  
  api:
    build:
      context: ./api/
      dockerfile: ./docker/Dockerfile.prod
    image: mpa-api-prod
    container_name: mpa-api-prod
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://mpa:password@database:5432/mpa

  database:
    image: postgres:13.1-alpine
    container_name: mpa-database-prod
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mpa
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mpa
