# ==== builder stage ====
FROM node:15.5-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# ==== server stage ====
FROM node:15.5-alpine as server

WORKDIR /app

COPY package*.json ./
RUN npm ci --production

COPY --from=builder /app/.next ./.next

CMD ["npm", "run", "start"]

EXPOSE 3000