FROM node:15.7-buster-slim

WORKDIR /app

# Prisma CLI dependency
RUN apt-get -qy update && apt-get -qy install openssl

COPY package.json package-lock.json ./

RUN npm ci

COPY ./docker/entry-point.sh /entry-point.sh
RUN chmod +x /entry-point.sh

ENTRYPOINT ["/entry-point.sh"]

CMD ["npm", "run", "dev"]