# This is a basic workflow to help you get started with Actions

name: add to projects

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: add to features
        if: github.event.label.name == 'feature'
        uses: alex-page/github-project-automation-plus@v0.5.1
        with:
          project: features
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: add to bugs
        if: github.event.label.name == 'bug'
        uses: alex-page/github-project-automation-plus@v0.5.1
        with:
          project: bugs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
